### ISSUE TITLE
Result file reorders original yaml file alphabetically for remove/replace operations

### ISSUE THREAD

**Issue by hajinsu9** [vmware-archive/yaml-patch#2]
When using the remove/replace operations the result file is reorganized alphabetically. This causes issues because in the pipeline file the order is important.

**Source YAML file**
```
---
jobs:
- name: my-job
  plan:
  - get: my-resource
  - task: first-task
    file: task1.yml
  - task: second-task
    file: task2.yml
```

**Operations File**
```
- op: replace
  path: /jobs/name=my-job/plan/task=second-task
  value:
    task: abc
    file: abc
```

**Expected Result YAML file**
```
jobs:
- name: my-job
  plan:
  - get: my-resource
  - task: first-task
    file: task1.yml
  - task: abc
    file: abc
```

**Actual Result YAML file**
```
jobs:
- name: my-job
  plan:
  - get: my-resource
  - file: task1.yml
    task: first-task
  - file: abc
    task: abc
```
# Steps to Reproduce
Copy and paste below code into a file and run using `go run FILENAME.go` in terminal
## Code
```
package main
import (
  "fmt"
  "log"
  yamlpatch "github.com/pivotal-cf/yaml-patch"
)
func main() {
  doc := []byte(`---
  jobs:
  - name: my-job
    plan:
    - get: my-resource
    - task: first-task
      file: task1.yml
    - task: second-task
      file: task2.yml
  `)

  ops := []byte(`---
  - op: replace
    path: /jobs/name=my-job/plan/task=second-task
    value:
      task: abc
      file: abc
  `)

  patch, err := yamlpatch.DecodePatch(ops)
  if err != nil {
    log.Fatalf("decoding patch failed: %s", err)
  }

  bs, err := patch.Apply(doc)
  if err != nil {
    log.Fatalf("applying patch failed: %s", err)
  }
  fmt.Println(string(bs))
}
```
